---
title: "Patient 1"
author: "dssrttn"
date: "2020-07-10"
output: 
  workflowr::wflow_html:
    code_folding: hide
---

```{r setup, message=FALSE, warning=FALSE}

knitr::opts_chunk$set(dev=c('png', 'pdf'), width=7, height=5)

```


```{r DIL mean for boxplot, message=FALSE, warning=FALSE}
library(plyr)
library(tidyverse)
library(ggplot2)
library(scales)
library(knitr)
library(kableExtra)
library(psych)
library(here)
library(jtools) # for linear regression output. not used so far
options(digits=3) # zeigt nur drei Zahlenwerte an
source("code/plottheme.R")
source("code/cbPalette.R")
source("code/lineplottheme.R")


DIL<- read_csv2('data/1/DIL.csv')
Boost <- read_csv2('data/1/Boost.csv')
Rectum <- read_csv2('data/1/Rectum.csv')
Bladder <- read_csv2('data/1/Bladder.csv')
XVI <- read_csv2('data/1/XVI.csv')
```


```{r setuffp}
Boost_mean_boxplot <- Boost
DIL_mean_boxplot <- DIL

Boost_mean_boxplot
DIL_mean_boxplot


DIL_mean_boxplot <- distinct(DIL_mean_boxplot, Mittelwert) # aus dem ursprünglichen tibble wird nur die column Mittelwert behalten
DIL_mean_boxplot <- DIL_mean_boxplot %>% select(Mittelwert_DIL = Mittelwert)
DIL_mean_boxplot

DIL_minus_Boost_mean_boxplot <- DIL_mean_boxplot %>% add_column(Mittelwert_Boost = Boost_mean_boxplot$Mittelwert)
DIL_minus_Boost_mean_boxplot

DIL_minus_Boost_mean_table <- ddply(DIL_minus_Boost_mean_boxplot, .(), transform, dilminusboost =  (Mittelwert_DIL-Mittelwert_Boost)/(Mittelwert_DIL[1]-Mittelwert_Boost[1]))
DIL_minus_Boost_mean_table

DIL_minus_Boost_mean_table <- DIL_minus_Boost_mean_table %>% mutate(.id = row_number())
DIL_minus_Boost_mean_table <- DIL_minus_Boost_mean_table %>% rename('Fraction' = '.id') #renmae column '.id' with 'Fraction'
DIL_minus_Boost_mean_table

y <- DIL_minus_Boost_mean_table$dilminusboost

ggplot(DIL_minus_Boost_mean_table, aes(x="" 
                                       ,y=y)) +
geom_boxplot() +
theme_classic()

#+
# plottheme 





DIL_minus_Boost_mean_table <- cut(DIL_minus_Boost_mean_table$dilminusboost, c(-Inf, 0.95, 0.96, 0.97, 0.98, 0.99, 1.00, 1.01, 1.02, 1.03, 1.04, 1.05, Inf), labels=c('<0.95%', '95-96%', '96-97%', '97-98%', '98-99%', '99-100%', '100-101%', '101-102%', '102-103%', '103-104%', '104-105%', '>105%'))  # benutzt dplyr, 7 Intervalle


DIL_minus_Boost_mean_table <- as.data.frame(DIL_minus_Boost_mean_table) %>%
  group_by(DIL_minus_Boost_mean_table, .drop = FALSE) %>% #.drop = FALSE ansonsten Fehlermeldung, weil  empty categories are dropped by default. You can change this behavior by adding .drop = FALSE
  dplyr::summarise(Numbers = n())  #%>% # %>% #=n())
#mutate(Nummers = rowSums(.[-1]))


DIL_minus_Boost_mean_table %>%
  knitr::kable(format ='html', caption = "", col.names = c("DIL minus boost", "Numbers")) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = FALSE)





```
