
---
title: "dilundboost"
output: 
  workflowr::wflow_html:
    code_folding: hide
---

```{r setup, message=FALSE}

knitr::opts_chunk$set(dev=c('png', 'pdf'), width=7, height=5)

```



```{r Relative dose changes in percen from the 1st fraction with DIL and boost mean lines,  width=7, height=5, dev=c('png', 'pdf'), message=FALSE}
library(plyr)
library(tidyverse)
library(ggplot2)
library(scales)
library(knitr)
library(kableExtra)
options(digits=3) # zeigt nur drei Zahlenwerte an


# The Color Universal Design from the University of Tokyo proposes the following palettes:
# The palette with grey from:
cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7")
   
  plottheme <- list(
     theme_classic() +
  theme(
    legend.title = element_blank(),
     legend.text = element_text(color = "black", size = rel(1)),
  plot.title =  element_blank(),  #element_text(color="black", size=14, face="bold.italic", family ="serif"), # Titel des Graphen
  axis.text.x = element_text(margin = unit(c(1.5, 0, 0, 0), "mm"), family = "serif", size=rel(2)), # X-Achsen-Bezeichnungs-Parameter
  axis.text.y = element_text(margin = unit(c(0, 1.5, 0, 0), "mm"), family = "serif", size=rel(2)), # Y-Achsen-Bezeichnungs-Parameter
  axis.title.x = element_text(margin = unit(c(1.5, 0, 0, 0), "mm"), family = "serif", size=rel(2)), 
  # X-Achsen-Beschriftungs-(groß)-Parameter
  axis.title.y = element_text(margin = unit(c(0, 2, 0, 0), "mm"), family = "serif", size=rel(2)), # Y-Achsen-Beschriftungs-(groß)-Parameter
  plot.margin = margin(0.5, 0.5, 0.5, 0.5, "cm"), # Abstände um den Graphen in top-right-bottom-left Orientierung
  axis.ticks = element_line(color = 'black', size = 0.5, linetype = 1), axis.ticks.length = unit(0.2, "cm"), # Teilstriche
  axis.line = element_line(color = 'black', size = 0.3, linetype = 1) # Achsenlinie
   )
  )



DIL_mean_rel <- read_csv2("data/DIL_1.csv") # read csv mit europaeischer Syntax. Auf das richtige package achten! 

DIL_mean_rel <- distinct(DIL_mean_rel, Mittelwert) # aus dem ursprünglichen tibble wird nur die column Mittelwert behalten


#ddply(DIL_absolut, .(), transform, relchange2 = ((100 / Mittelwert[1]) * Mittelwert) - 100) # alternative Berechnung fuer relative Differenzen zum Ausgangswert in der 1. Reihe 

DIL_mean_rel <- ddply(DIL_mean_rel, .(), transform, relchange = ((Mittelwert - Mittelwert[1]) / Mittelwert[1]) * 100) # relative Differenzen zum Ausgangswert in der 1. Reihe werden berechnet

DIL_mean_rel_table <- ddply(DIL_mean_rel, .(), transform, relchange = ((Mittelwert - Mittelwert[1]) / Mittelwert[1]) * 100) 



DIL_mean_rel_table <- DIL_mean_rel_table %>% rename('Fraction' = '.id') #renmae column '.id' with 'Fraction'

DIL_mean_rel_table[1:14, 1] = (1:14) 

DIL_mean_rel_table %>%
  kable(align = c("ccccccccc"), escape = FALSE, format ='html', caption = "DIL descriptive statistics") %>%
kable_styling(bootstrap_options = c("striped", "hover", "condensed"), 
    full_width = TRUE) 



Boost_mean_rel <- read_csv2("data/BoostA1n_1.csv") # read csv mit europaeischer Syntax. Auf das richtige package achten! 

Boost_mean_rel <- distinct(Boost_mean_rel, Mittelwert) # aus dem ursprünglichen tibble wird nur die column Mittelwert behalten


#ddply(DIL_absolut, .(), transform, relchange2 = ((100 / Mittelwert[1]) * Mittelwert) - 100) # alternative Berechnung fuer relative Differenzen zum Ausgangswert in der 1. Reihe 

Boost_mean_rel <- ddply(Boost_mean_rel, .(), transform, relchange = ((Mittelwert - Mittelwert[1]) / Mittelwert[1]) * 100) # relative Differenzen zum Ausgangswert in der 1. Reihe werden berechnet

Boost_mean_rel_table <- ddply(Boost_mean_rel, .(), transform, relchange = ((Mittelwert - Mittelwert[1]) / Mittelwert[1]) * 100) 



Boost_mean_rel_table <- Boost_mean_rel_table %>% rename('Fraction' = '.id') #renmae column '.id' with 'Fraction'

Boost_mean_rel_table[1:14, 1] = (1:14) 

Boost_mean_rel_table %>%
  kable(align = c("ccccccccc"), escape = FALSE, format ='html', caption = "Boost descriptive statistics") %>%
kable_styling(bootstrap_options = c("striped", "hover", "condensed"), 
    full_width = TRUE) 




ggplot() + 
  geom_line(data = DIL_mean_rel_table, aes(x = 1:14, y = DIL_mean_rel$relchange, color = "DIL")) +
  geom_line(data = Boost_mean_rel_table , aes(x = 1:14, y = Boost_mean_rel$relchange, color = "Boost")) +
 geom_point(data = DIL_mean_rel_table, aes(x = 1:14, y = DIL_mean_rel$relchange, color = "DIL")) +
  geom_point(data = Boost_mean_rel_table , aes(x = 1:14, y = Boost_mean_rel$relchange, color = "Boost")) +
      scale_colour_manual(values=cbPalette) +  # To use for line and point colors, add
   expand_limits(y = c(-2, 2)) +
  scale_y_continuous(breaks = seq(-2, 2, 1.0), labels=function(x) paste0(x,"%")) + #labels=function(x) paste0(x,"%") adds percent symbol, but without multiplying it with 100, like when one does: scale_y_continuous(labels = scales::percent)
    scale_x_continuous(breaks = c(1,5,10,14))  + # adds only specific ticks
      geom_abline(intercept = 0, slope = 0, lty=2) + # horizontale Linie ohne Steigung, da slope = 0 
  ggtitle("DIL - Relative dose changes in percent from the 1st fraction with DIL") +
  xlab("Fraction") + # X-Achsen-Beschriftung
  ylab("Relative dose changes") +   #+ # Y-Achsen-Beschriftung
  plottheme
  
   


```


