---
title: "error"
author: "Mein Vorname"
date: "2020-06-30"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

## Introduction

```{r}

```

```{r DIL Mittelwert error bars, , width=7, height=5, dev=c('png', 'pdf'), echo = FALSE}
library(ggplot2)
#library(scales)

DIL_1 <- read.csv2('data/1/DIL.csv', header=TRUE, stringsAsFactors=FALSE, sep=";", dec=",", row.names="Dosisname")

data <- data.frame(
x <- (1:14),
y <- DIL_1$Mittelwert,
y.sd <- DIL_1$sigma)
  


#x
#y
#data

ggplot(data, aes(x, y)) + 
  geom_point() +
  geom_line() +
 expand_limits(y = c(75.0, 78)) +
   geom_errorbar(aes(ymin=y-y.sd, ymax=y+y.sd), width=.2,
                 position=position_dodge(.9)) +
  
  scale_y_continuous(breaks = seq(75.0,78.0,1.0)) +
  scale_x_continuous(breaks = c(1, 5,10, 14)) +  # für jedes x ein tick
geom_abline(intercept = 76.23, slope = 0, lty=2) + # horizontale Linie ohne Steigung, da slope = 0 
   annotate("text", x = 13.2, y = 76.1, cex =rel(4), label = "Boost constraint") +
  theme_classic() +
  theme(
  plot.title =  element_blank(), #element_text(color="black", size=14, face="bold.italic", family ="serif"), # Titel des Graphen
  axis.text.x = element_text(margin = unit(c(1.5, 0, 0, 0), "mm"), family = "serif", size=rel(2)), # X-Achsen-Bezeichnungs-Parameter
  axis.text.y = element_text(margin = unit(c(0, 1.5, 0, 0), "mm"), family = "serif", size=rel(2)), # Y-Achsen-Bezeichnungs-Parameter
  axis.title.x = element_text(margin = unit(c(1.5, 0, 0, 0), "mm"), family = "serif", size=rel(2)), 
  # X-Achsen-Beschriftungs-(groß)-Parameter
  axis.title.y = element_text(margin = unit(c(0, 2, 0, 0), "mm"), family = "serif", size=rel(2)), # Y-Achsen-Beschriftungs-(groß)-Parameter
  plot.margin = margin(0.5, 0.5, 0.5, 0.5, "cm"), # Abstände um den Graphen in top-right-bottom-left Orientierung
  axis.ticks = element_line(color = 'black', size = 0.5, linetype = 1), axis.ticks.length = unit(0.13, "cm"), # Teilstriche
 # line = element_blank() # keine Achsenlinien
 axis.line = element_line(color = 'black', size = 0.3, linetype = 1) # Achsenlinie
   ) +
 xlab("Fraction") + # X-Achsen-Beschriftung
  ylab("Dose in Gray")  #+ # Y-Achsen-Beschriftung

```
