---
title: "First-Analysis"
output: 
  workflowr::wflow_html:
    code_folding: hide
---

```{r setup, message=FALSE}

knitr::opts_chunk$set(dev=c('png', 'pdf'), width=7, height=5)

```


### DIL boost mean - boxplot

```{r DIL Boxplot, message=FALSE}
library(tidyverse)

DIL_mean_boxplot <- read_csv2('data/DIL_1.csv')

max <-max(DIL_mean_boxplot$Mittelwert)
min <-min(DIL_mean_boxplot$Mittelwert)



par(bty="n") # keinen Rahmen
par(family="serif") # Schriftart
par(mar = c(2, 8, 2, 2)) # Abstände um den Plot. 2. Position y-Achse
par(mgp=c(4.2,1,0)) # mpg: Abstand Label zu Achse
boxplot(DIL_mean_boxplot$Mittelwert, 
        ylab= "Dose in Gray", #y-Achse-Beschriftung  
        #yaxt="n", #suppresses y-axis. Brauch ich das? 
        col="transparent", #Farbe des Boxplots
        las = 2, # horizontale Markierung der Tick-Beschriftungen
         ylim=c(min(0.995*min), max(1.005*max)), # y-Achse range
        cex.lab = 2, # Größe Label-Beschriftung
        cex.axis = 1.5 # Größe Achsenbeschriftungen
        #mgp=c(3,1,0) # mpg: Abstand Label zu Achse
     # , xpd = TRUE
      #labels = FALSE
        )

```



### DIL boost mean - histogram with density curve


```{r DIL Histogram, message=FALSE}
par(family="serif") # Schriftart
par(mar = c(5, 5, 2, 2)) # Abstände um den Plot. 2. Po´ition y-Achse
par(mgp=c(3,1,0)) # mpg: Abstand Label zu Achse
hist(DIL_mean_boxplot$Mittelwert, 
    main="",
    #DIL Mittelwert" 
     ylab="Density", xlab="Dosis in Gray", mgp=c(3,1,0), las = 1, freq = FALSE, ylim=c(0, 2), xlim=c(76.2, 77.6), cex.lab=2, cex.axis=1.5, col = "transparent")
rug(jitter(DIL_mean_boxplot$Mittelwert))
lines(density(DIL_mean_boxplot$Mittelwert), col="black", lwd=2)
#cex.lab=1.5, cex.axis=1.5
```
