---
title: "kable"
author: "Mein Vorname"
date: "2020-07-01"
tables: true
output: 
  workflowr::wflow_html:
    code_folding: hide
---

## Introduction


The following table shows some characteristic descriptive statistics regarding the dominant intraprostatic lesion. The mean absolute deviation is calculated regarding the boost constraint.

```{r DIL descriptive statistics, results='asis', message=FALSE}
library(knitr)
#options(kableExtra.latex.load_packages = FALSE)
library(kableExtra)
library(psych)
library(tidyverse)
library(dplyr)
library(DescTools)
options(digits=3) # zeigt nur drei Zahlenwerte an

DIL_1 <- read_csv2('data/DIL_1.csv')# header=TRUE, stringsAsFactors=FALSE, sep=";", dec=",", row.names="Dosisname")
df <- data.frame(DIL_1)



DIL_1 <- DIL_1 %>% 
  select(Mittelwert, D_95, sigma, D_99, D_1)

MAD_DIL_1 <- DIL_1 %>%
  select(Mittelwert)
MAD_DIL_1 <- MeanAD(DIL_1$Mittelwert, center = 76.23) # muss an dieser Stelle stehen, ansonsten Fehlermeldung



DIL_1<- describe(DIL_1)


DIL_1 <- DIL_1 %>% rename(Numbers = n, Mean = mean, 'Standard deviation' = sd, Median = median, 'Standard errors' = se, Minimum = min, Maximum = max, Range = range)

DIL_1 <- DIL_1 %>% 
  select(Numbers,	Mean,	'Standard deviation',	Median,	Minimum,	Maximum, Range, 'Standard errors')


DIL_1 <- DIL_1 %>% add_column(MAD_DIL_1, .after = 'Standard errors')
DIL_1 <- DIL_1 %>% rename('Mean absolute deviation' = MAD_DIL_1)

DIL_1[2:5, 9] = NA #Befehl um in einem dataframe, hier 2.-6. Zeile und 9. Reihe einen neuen Wert (hier NA) eibnzusetzen





DIL_1 %>%
  kable(align = c("ccccccccc"), escape = FALSE, format ='html', caption = "DIL descriptive statistics") %>%
kable_styling(bootstrap_options = c("striped", "hover", "condensed"), 
    full_width = TRUE) 
```




```{r Boost descriptive statistics, results='asis', message=FALSE}
library(knitr)
#options(kableExtra.latex.load_packages = FALSE)
library(kableExtra)
library(psych)
library(tidyverse)
library(dplyr)
library(DescTools)
options(digits=3) # zeigt nur drei Zahlenwerte an

Boost_descsta <- read_csv2('data/BoostA1n_1.csv')
Boost_descsta <- data.frame(Boost_descsta)



Boost_descsta <- Boost_descsta %>% 
  select(Mittelwert, D_95, sigma, D_99, D_1)

MAD_Boost <- Boost_descsta %>%
  select(Mittelwert)
MAD_Boost <- MeanAD(Boost_descsta$Mittelwert, center = 76.23) # muss an dieser Stelle stehen, ansonsten Fehlermeldung



Boost_descsta<- describe(Boost_descsta)


Boost_descsta <- Boost_descsta %>% rename(Numbers = n, Mean = mean, 'Standard deviation' = sd, Median = median, 'Standard errors' = se, Minimum = min, Maximum = max, Range = range)

Boost_descsta <- Boost_descsta %>% 
  select(Numbers,	Mean,	'Standard deviation',	Median,	Minimum,	Maximum, Range, 'Standard errors')


Boost_descsta <- Boost_descsta %>% add_column(MAD_Boost, .after = 'Standard errors')
Boost_descsta <- Boost_descsta %>% rename('Mean absolute deviation' = MAD_Boost)

Boost_descsta[2:5, 9] = NA #Befehl um in einem dataframe, hier 2.-6. Zeile und 9. Reihe einen neuen Wert (hier NA) eibnzusetzen





Boost_descsta %>%
  kable(align = c("ccccccccc"), escape = FALSE, format ='html', caption = "Boost descriptive statistics") %>%
kable_styling(bootstrap_options = c("striped", "hover", "condensed"), 
    full_width = TRUE) 
```
