---
title: "DILdurchBoost"
author: "Mein Vorname"
date: "2020-07-10"
output: 
  workflowr::wflow_html:
    code_folding: hide
---

```{r setup, message=FALSE}

knitr::opts_chunk$set(dev=c('png', 'pdf'), width=7, height=5)

```


```{r DIL Boxplot, message=FALSE}
library(plyr)
library(tidyverse)
library(ggplot2)
library(scales)
library(knitr)
library(kableExtra)
#options(digits=3) # zeigt nur drei Zahlenwerte an

DIL_min_boxplot <- read_csv2('data/DIL_1.csv')
DIL_min_boxplot  # Tibble with all DIL parameters 

#max <-max(DIL_mean_boxplot$Mittelwert)
#min <-min(DIL_mean_boxplot$Mittelwert)

Boost_mean_boxplot <- read_csv2('data/BoostA1n_1.csv')
Boost_mean_boxplot # Tibble with all Boost parameters 

DIL_min_boxplot <- distinct(DIL_min_boxplot, D_min) # aus dem ursprünglichen tibble wird nur die column Mittelwert behalten
DIL_min_boxplot <- DIL_min_boxplot %>% select(Minimum_DIL = D_min)
DIL_min_boxplot # Tibble with DIL_min parameter



#Boost_mean_boxplot <- distinct(Boost_mean_boxplot, Mittelwert)
#Boost_mean_boxplot <-  Boost_mean_boxplot %>% select(Mittelwert_Boost = Mittelwert)
#Boost_mean_boxplot


DIL_min_Boost_mean_boxplot <- DIL_min_boxplot %>% add_column(Mittelwert_Boost = Boost_mean_boxplot$Mittelwert)
DIL_min_Boost_mean_boxplot # Tibble with DIL_min and boost_mean parameter

#DIL_Boost_mean_rel_boxplot <- ddply(DIL_Boost_mean_boxplot,(), transform, Mittelwert.1 = (DIL_mean_boxplot / Boost_mean_boxplot[1]))

#DIL_mean_rel_table <- ddply(DIL_Boost_mean_boxplot, .(), transform, Fraction = 1:14) # adding column with fraction
#´DIL_mean_rel_table                            
                            #relchange = ((Mittelwert - Mittelwert[1]) / Mittelwert[1]) * 100) 

DIL_min_Boost_mean_rel_table <- ddply(DIL_min_Boost_mean_boxplot, .(), transform, dilminboostmean = (Minimum_DIL/ Mittelwert_Boost[1])) 
DIL_min_Boost_mean_rel_table # Tibble with DIL_min and boost_mean parameter and relation of DIL_min[n] to Boost_mean[1]





max <-max(DIL_min_Boost_mean_rel_table$dilminboostmean)
min <-min(DIL_min_Boost_mean_rel_table$dilminboostmean)

par(bty="n") # keinen Rahmen
par(family="serif") # Schriftart
par(mar = c(5, 6.5, 2, 2)) # Abstände um den Plot. 2. Position y-Achse
par(mgp=c(5,1,0)) # mpg: Abstand Label zu Achse
boxplot(DIL_min_Boost_mean_rel_table$dilminboostmean, # Boxpplot with relation of DIL_min[n] to Boost_mean[1]
        ylab= "Relation Dil_min to Boost[1]", #y-Achse-Beschriftung  
        #yaxt="n", #suppresses y-axis. Brauch ich das? 
        col="transparent", #Farbe des Boxplots
        las = 2, # horizontale Markierung der Tick-Beschriftungen
      #ylim = c(0, 1),
      #ylim=c(0.95, 1.0),
         ylim=c(min(0.995*min), max(1.005*max)), # y-Achse range
        cex.lab = 2, # Größe Label-Beschriftung
        cex.axis = 1.5, # Größe Achsenbeschriftungen
        mgp=c(2.5,0.2,0) # mpg: Abstand Label zu Achse
     # , xpd = TRUE
      #labels = FALSE
        )



DIL_min_Boost_mean_rel_table <- DIL_min_Boost_mean_rel_table %>% rename('Fraction' = '.id') #renmae column '.id' with 'Fraction'
DIL_min_Boost_mean_rel_table[1:14, 1] = (1:14) 
DIL_min_Boost_mean_rel_table # Tibble with DIL_min and boost_mean parameter and relation of DIL_min[n] to Boost_mean[1] and Fraction


DIL_min_Boost_mean_rel_table %>%
  kable(align = c("ccccccccc"), escape = FALSE, format ='html', caption = "DIL durch Boost[1") %>%
kable_styling(bootstrap_options = c("striped", "hover", "condensed"), 
   full_width = TRUE) 

DIL_min_Boost_mean_rel_table <- cut(DIL_min_Boost_mean_rel_table$dilminboostmean, c(-Inf, 0.95, 0.96, 0.97, 0.98, 0.99, 1.00, 1.01, 1.02, 1.03, 1.04, 1.05, Inf), labels=c('<95%', '95-96%', '96-97%', '97-98%', '98-99%', '99-100%', '100-101%', '101-102%', '102-103%', '103-104%', '104-105%', '>105%'))  # benutzt dplyr, 7 Intervalle 


DIL_min_Boost_mean_rel_table <- as.data.frame(DIL_min_Boost_mean_rel_table) %>%  
group_by(DIL_min_Boost_mean_rel_table, .drop = FALSE) %>% #.drop = FALSE ansonsten Fehlermeldung, weil  empty categories are dropped by default. You can change this behavior by adding .drop = FALSE
dplyr::summarise(Numbers = n())  #%>% # %>% #=n())   
#mutate(Nummers = rowSums(.[-1]))


DIL_min_Boost_mean_rel_table %>%
 knitr::kable(format ='html', caption = "", col.names = c("DIL durch boost_1", "Numbers")) %>%
kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = FALSE) 




```
