---
title: "Rechnungen"
author: "Mein Vorname"
date: "2020-06-25"
output: 
  workflowr::wflow_html:
    code_folding: hide
---   


```{r setup, message=FALSE}

knitr::opts_chunk$set(dev=c('png', 'pdf'), width=7, height=5)

```
 
## Tibble - Dosisbereiche 

### DIL boost constraint 
#### DIL boost constraint - table

```{r DIL boost constraint - table, message=FALSE}
library(dplyr)
library(tidyverse)
library(knitr)
library(kableExtra)

DIL_constraint<- read_csv2('data/DIL_1.csv')

DIL_constraint <- cut(DIL_constraint$Mittelwert, c(-Inf, 76.23, 76.23*1.01, 76.23*1.02, 76.23*1.03, 76.23*1.04, 76.23*1.05, Inf), labels=c('< 76.23 Gy', 'within + 1% of constraint', 'within + 2% of constraint', 'within + 3% of constraint', 'within + 4% of constraint', 'within + 5% of constraint', '> + 5% of constraint'))  # benutzt dplyr, 7 Intervalle 


DIL_constraint <- as.data.frame(DIL_constraint) %>%  
group_by(DIL_constraint, .drop = FALSE) %>% #.drop = FALSE ansonsten Fehlermeldung, weil  empty categories are dropped by default. You can change this behavior by adding .drop = FALSE
dplyr::summarise(Numbers = n())  #%>% # %>% #=n())   
#mutate(Nummers = rowSums(.[-1]))

DIL_constraint %>%
 knitr::kable(format ='html', caption = "", col.names = c("DIL boost constraint", "Numbers")) %>%
kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = FALSE) 



```

### Bladder D_10 (60.0 Gy) constraint 
#### Bladder D_10 constraint - table


``` {r Bladder D_10 constraint - table, message=FALSE}
library(tidyverse)

Bladder_constraint <- read.csv2('data/Bladder_1.csv')

Bladder_constraint<- cut(Bladder_constraint$D_10, c(-Inf, 60*0.95, 60, 60*1.05, Inf), labels=c('outside - 5% of constraint', '< 60 Gy', '> 60 Gy', 'outside + 5% of constraint'))  # benutzt dplyr, 2 Intervalle 


Bladder_constraint <- as.data.frame(Bladder_constraint) %>%  
group_by(Bladder_constraint, .drop = FALSE) %>% #.drop = FALSE ansonsten Fehlermeldung, weil  empty categories are dropped by default. You can change this behavior by adding .drop = FALSE
dplyr::summarise(Numbers = n())  #%>% # %>% #=n())   
#mutate(Nummers = rowSums(.[-1]))

Bladder_constraint %>%
 knitr::kable(format = 'html', caption = "", col.names = c("Bladder D_10 constraint", "Numbers")) %>%
kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = FALSE) 


```



##### Bladder D_10 constraint - boxplot

``` {r Bladder D_10 constraint - boxplot, message=FALSE}


Bladder_constraint <- read.csv2('data/Bladder_1.csv') # need to be here for ylim!

max <-max(Bladder_constraint$D_10)
min <-min(Bladder_constraint$D_10)


par(bty="n") # keinen Rahmen
par(family="serif") # Schriftart
par(mar = c(2, 8, 2, 2)) # Abstände um den Plot. 2. Position y-Achse
par(mgp=c(4.2,1,0)) # mpg: Abstand Label zu Achse
boxplot(Bladder_constraint$D_10, 
        ylab= "Dosis in Gray", #y-Achse-Beschriftung  
        #yaxt="n", #suppresses y-axis. Brauch ich das? 
        col="transparent", #Farbe des Boxplots
        las = 2, # horizontale Markierung der Tick-Beschriftungen
       ylim=c(min(0.995*min), max(1.005*max)), 
        # ylim=c(min(Bladder_constraint$D_10), max(Bladder_constraint$D_10)), # y-Achse range
        cex.lab = 2, # Größe Label-Beschriftung
        cex.axis = 1.5 # Größe Achsenbeschriftungen
        #mgp=c(3,1,0) # mpg: Abstand Label zu Achse
     # , xpd = TRUE
      #labels = FALSE
        )


```



### Rectum D_5 (72.4 Gy) constraint
#### Rectum RV cum PTV D_5 constraint - table

``` {r Rectum RV cum PTV D_5 constraint - table, message=FALSE}
  

Rectum_D5_constraint <- read.csv2('data/Rectum_1.csv')

Rectum_D5_constraint<- cut(Rectum_D5_constraint$D_5, c(-Inf, 72.4*0.95, 72.4, 72.4*1.05, Inf), labels=c('outside - 5% of constraint', '< 72.4 Gy', '> 72.4 Gy', 'outside + 5% of constraint'))  # benutzt dplyr, 2 Intervalle 

Rectum_D5_constraint <- as.data.frame(Rectum_D5_constraint) %>%  
group_by(Rectum_D5_constraint, .drop = FALSE) %>% #.drop = FALSE ansonsten Fehlermeldung, weil  empty categories are dropped by default. You can change this behavior by adding .drop = FALSE
dplyr::summarise(Numbers = n())  #%>% # %>% #=n())   
#mutate(Nummers = rowSums(.[-1]))

Rectum_D5_constraint %>%
 knitr::kable(format ='html', caption = "", col.names = c("Rectum D_5 constraint", "Numbers")) %>%
kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = FALSE) 


```


#### Rectum RV cum PTV D_5 constraint - boxplot

``` {r Rectum RV cum PTV D_5 constraint - boxplot, message=FALSE}
Rectum_D5_constraint<- read.csv2('data/Rectum_1.csv')

max <-max(Rectum_D5_constraint$D_5)
#max
min <-min(Rectum_D5_constraint$D_5)
#min


par(bty="n") # keinen Rahmen
par(family="serif") # Schriftart
par(mar = c(2, 8, 2, 2)) # Abstände um den Plot. 2. Position y-Achse
par(mgp=c(4.2,1,0)) # mpg: Abstand Label zu Achse
boxplot(Rectum_D5_constraint$D_5, 
        ylab= "Dosis in Gray", #y-Achse-Beschriftung  
        #yaxt="n", #suppresses y-axis. Brauch ich das? 
        col="transparent", #Farbe des Boxplots
        las = 2, # horizontale Markierung der Tick-Beschriftungen
        ylim=c(min(0.995*min), max(1.005*max)), 
         #ylim=range(pretty(c(0, dat)))
       #  ylim=range(pretty(c(60, Rectum_D5_constraint))),
      #  ylim=c(min(Rectum_D5_constraint$D_5), max(Rectum_D5_constraint$D_5)), # y-Achse range
      #ylim=c(min(Rectum_D5_constraint$D_5[[i]]),max(Rectum_D5_constraint$D_5[[i]])),
       cex.lab = 2, # Größe Label-Beschriftung
        cex.axis = 1.5 # Größe Achsenbeschriftungen
        #mgp=c(3,1,0) # mpg: Abstand Label zu Achse
     # , xpd = TRUE
      #labels = FALSE
        )



```




### Penile bulb D_60 (70,0 Gy) constraint
#### Penile bulb D_60 constraint- table

``` {r Penile bulb D_60 constraint- table, message=FALSE}
library(tidyverse)

PenileBulb_D60_constraint <- read.csv2('data/PenisBulb_1.csv')

PenileBulb_D60_constraint<- cut(PenileBulb_D60_constraint$D_60, c(-Inf, 70.0*0.95, 70.0, 70*1.05, Inf), labels=c('outside - 5% of constraint', '< 70.0 Gy', '> 70.0 Gy', 'outside 5 5% of constraint'))  # benutzt dplyr, 2 Intervalle 

PenileBulb_D60_constraint <- as.data.frame(PenileBulb_D60_constraint) %>%  
group_by(PenileBulb_D60_constraint, .drop = FALSE) %>% #.drop = FALSE ansonsten Fehlermeldung, weil  empty categories are dropped by default. You can change this behavior by adding .drop = FALSE
dplyr::summarise(Numbers = n())  #%>% # %>% #=n())   
#mutate(Nummers = rowSums(.[-1]))

PenileBulb_D60_constraint %>%
 knitr::kable(format ='html', caption = "", col.names = c("Penile Bulb D_60 constraint", "Numbers")) %>%
kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = FALSE) 

```


##### Penile bulb D_60 constraint - boxplot

```{r Penile bulb D_60 constraint - boxplot, message=FALSE}

PenileBulb_D60_constraint <- read.csv2('data/PenisBulb_1.csv')

max <-max(PenileBulb_D60_constraint$D_60)
min <-min(PenileBulb_D60_constraint$D_60)


par(bty="n") # keinen Rahmen
par(family="serif") # Schriftart
par(mar = c(2, 8, 2, 2)) # Abstände um den Plot. 2. Position y-Achse
par(mgp=c(4.2,1,0)) # mpg: Abstand Label zu Achse
boxplot(PenileBulb_D60_constraint$D_60, 
        ylab= "Dosis in Gray", #y-Achse-Beschriftung  
        #yaxt="n", #suppresses y-axis. Brauch ich das? 
        col="transparent", #Farbe des Boxplots
        las = 2, # horizontale Markierung der Tick-Beschriftungen
        ylim=c(min(0.99*min), max(1.01*max)), 
       cex.lab = 2, # Größe Label-Beschriftung
        cex.axis = 1.5 # Größe Achsenbeschriftungen
        #mgp=c(3,1,0) # mpg: Abstand Label zu Achse
     # , xpd = TRUE
      #labels = FALSE
        )



```

