---
title: "Rechnungen"
author: "Mein Vorname"
date: "2020-06-25"
output: 
  workflowr::wflow_html:
    code_folding: hide
---



```{r setup, message=FALSE}

knitr::opts_chunk$set(dev=c('png', 'pdf'), width=7, height=5)

```



```{r Relative dose changes in Grey from the 1st fraction with DIL,  width=7, height=5, dev=c('png', 'pdf'), message=FALSE}
library(plyr)
library(tidyverse)
library(ggplot2)
library(scales)
library(knitr)
library(kableExtra)
options(digits=3) # zeigt nur drei Zahlenwerte an

DIL_mean_rel <- read_csv2("data/DIL_1.csv") # read csv mit europaeischer Syntax. Auf das richtige package achten! 

DIL_mean_rel <- distinct(DIL_mean_rel, Mittelwert) # aus dem ursprünglichen tibble wird nur die column Mittelwert behalten


#ddply(DIL_absolut, .(), transform, relchange2 = ((100 / Mittelwert[1]) * Mittelwert) - 100) # alternative Berechnung fuer relative Differenzen zum Ausgangswert in der 1. Reihe 

DIL_mean_rel <- ddply(DIL_mean_rel, .(), transform, relchange = ((Mittelwert - Mittelwert[1]) / Mittelwert[1]) * 100) # relative Differenzen zum Ausgangswert in der 1. Reihe werden berechnet

DIL_mean_rel_table <- ddply(DIL_mean_rel, .(), transform, relchange = ((Mittelwert - Mittelwert[1]) / Mittelwert[1]) * 100) 



DIL_mean_rel_table <- DIL_mean_rel_table %>% rename('Fraction' = '.id') #renmae column '.id' with 'Fraction'

DIL_mean_rel_table[1:14, 1] = (1:14) 

DIL_mean_rel_table %>%
  kable(align = c("ccccccccc"), escape = FALSE, format ='html', caption = "DIL descriptive statistics") %>%
kable_styling(bootstrap_options = c("striped", "hover", "condensed"), 
    full_width = TRUE) 



x <- (1:14)
y <- DIL_mean_rel$relchange

ggplot(DIL_mean_rel,aes(x=x #DIL_relabs$x
                      ,y=y )) + #DIL_relabs$abschange)) +
   geom_segment( aes(x=x, xend=x, y=0, yend=y), color="black") + # Striche von der Hoehe y bis zu den Punkten
    geom_point() +
  #geom_line() +
 expand_limits(y = c(-2, 2)) +
  scale_y_continuous(breaks = seq(-2, 2, 1.0), labels=function(x) paste0(x,"%")) + #labels=function(x) paste0(x,"%") adds percent symbol, but without multiplying it with 100, like when one does: scale_y_continuous(labels = scales::percent)
    scale_x_continuous(breaks = c(1,5,10,14))  + # adds only specific ticks
  geom_abline(intercept = 0, slope = 0, lty=2) + # horizontale Linie ohne Steigung, da slope = 0 
    theme_classic() +
  theme(
  plot.title =  element_blank(),  #element_text(color="black", size=14, face="bold.italic", family ="serif"), # Titel des Graphen
  axis.text.x = element_text(margin = unit(c(1.5, 0, 0, 0), "mm"), family = "serif", size=rel(2)), # X-Achsen-Bezeichnungs-Parameter
  axis.text.y = element_text(margin = unit(c(0, 1.5, 0, 0), "mm"), family = "serif", size=rel(2)), # Y-Achsen-Bezeichnungs-Parameter
  axis.title.x = element_text(margin = unit(c(1.5, 0, 0, 0), "mm"), family = "serif", size=rel(2)), 
  # X-Achsen-Beschriftungs-(groß)-Parameter
  axis.title.y = element_text(margin = unit(c(0, 2, 0, 0), "mm"), family = "serif", size=rel(2)), # Y-Achsen-Beschriftungs-(groß)-Parameter
  plot.margin = margin(0.5, 0.5, 0.5, 0.5, "cm"), # Abstände um den Graphen in top-right-bottom-left Orientierung
  axis.ticks = element_line(color = 'black', size = 0.5, linetype = 1), axis.ticks.length = unit(0.2, "cm"), # Teilstriche
  axis.line = element_line(color = 'black', size = 0.3, linetype = 1) # Achsenlinie
   ) +
  ggtitle("DIL - Relative dose changes in percent from the 1st fraction with DIL") +
  xlab("Fraction") + # X-Achsen-Beschriftung
  ylab("Relative dose changes")   #+ # Y-Achsen-Beschriftung
```



```{r DIL Boxplot, message=FALSE}
library(tidyverse)

DIL_mean_boxplot <- read_csv2('data/DIL_1.csv')

max <-max(DIL_mean_boxplot$Mittelwert)
min <-min(DIL_mean_boxplot$Mittelwert)



par(bty="n") # keinen Rahmen
par(family="serif") # Schriftart
par(mar = c(5, 6, 2, 2)) # Abstände um den Plot. 2. Position y-Achse
par(mgp=c(4.2,1,0)) # mpg: Abstand Label zu Achse
boxplot(DIL_mean_boxplot$Mittelwert, 
        ylab= "Dose in Gray", #y-Achse-Beschriftung  
        #yaxt="n", #suppresses y-axis. Brauch ich das? 
        col="transparent", #Farbe des Boxplots
        las = 2, # horizontale Markierung der Tick-Beschriftungen
         ylim=c(min(0.995*min), max(1.005*max)), # y-Achse range
        cex.lab = 2, # Größe Label-Beschriftung
        cex.axis = 1.5, # Größe Achsenbeschriftungen
        mgp=c(2.5,0.2,0) # mpg: Abstand Label zu Achse
     # , xpd = TRUE
      #labels = FALSE
        )

```






```{r Relative dose changes in Grey from the 1st fraction with DIL d 95,  width=7, height=5, dev=c('png', 'pdf'), message=FALSE}
library(plyr)
library(tidyverse)
library(ggplot2)
library(scales)
library(knitr)
library(kableExtra)
options(digits=3) # zeigt nur drei Zahlenwerte an

Boost_mean_rel <- read_csv2("data/BoostA1n_1.csv") # read csv mit europaeischer Syntax. Auf das richtige package achten! 

Boost_mean_rel <- distinct(Boost_mean_rel, Mittelwert) # aus dem ursprünglichen tibble wird nur die column Mittelwert behalten


#ddply(DIL_absolut, .(), transform, relchange2 = ((100 / Mittelwert[1]) * Mittelwert) - 100) # alternative Berechnung fuer relative Differenzen zum Ausgangswert in der 1. Reihe 

Boost_mean_rel <- ddply(Boost_mean_rel, .(), transform, relchange = ((Mittelwert - Mittelwert[1]) / Mittelwert[1]) * 100) # relative Differenzen zum Ausgangswert in der 1. Reihe werden berechnet

Boost_mean_rel_table <- ddply(Boost_mean_rel, .(), transform, relchange = ((Mittelwert - Mittelwert[1]) / Mittelwert[1]) * 100) 



Boost_mean_rel_table <- Boost_mean_rel_table %>% rename('Fraction' = '.id') #renmae column '.id' with 'Fraction'

Boost_mean_rel_table[1:14, 1] = (1:14) 

Boost_mean_rel_table %>%
  kable(align = c("ccccccccc"), escape = FALSE, format ='html', caption = "Boost descriptive statistics") %>%
kable_styling(bootstrap_options = c("striped", "hover", "condensed"), 
    full_width = TRUE) 



x <- (1:14)
y <- Boost_mean_rel$relchange

ggplot(Boost_mean_rel,aes(x=x #DIL_relabs$x
                      ,y=y )) + #DIL_relabs$abschange)) +
   geom_segment( aes(x=x, xend=x, y=0, yend=y), color="black") + # Striche von der Hoehe y bis zu den Punkten
    geom_point() +
  #geom_line() +
 expand_limits(y = c(-2, 2)) +
  scale_y_continuous(breaks = seq(-2, 2, 1.0), labels=function(x) paste0(x,"%")) + #labels=function(x) paste0(x,"%") adds percent symbol, but without multiplying it with 100, like when one does: scale_y_continuous(labels = scales::percent)
    scale_x_continuous(breaks = c(1,5,10,14))  + # adds only specific ticks
  geom_abline(intercept = 0, slope = 0, lty=2) + # horizontale Linie ohne Steigung, da slope = 0 
    theme_classic() +
  theme(
  plot.title =  element_blank(),  #element_text(color="black", size=14, face="bold.italic", family ="serif"), # Titel des Graphen
  axis.text.x = element_text(margin = unit(c(1.5, 0, 0, 0), "mm"), family = "serif", size=rel(2)), # X-Achsen-Bezeichnungs-Parameter
  axis.text.y = element_text(margin = unit(c(0, 1.5, 0, 0), "mm"), family = "serif", size=rel(2)), # Y-Achsen-Bezeichnungs-Parameter
  axis.title.x = element_text(margin = unit(c(1.5, 0, 0, 0), "mm"), family = "serif", size=rel(2)), 
  # X-Achsen-Beschriftungs-(groß)-Parameter
  axis.title.y = element_text(margin = unit(c(0, 2, 0, 0), "mm"), family = "serif", size=rel(2)), # Y-Achsen-Beschriftungs-(groß)-Parameter
  plot.margin = margin(0.5, 0.5, 0.5, 0.5, "cm"), # Abstände um den Graphen in top-right-bottom-left Orientierung
  axis.ticks = element_line(color = 'black', size = 0.5, linetype = 1), axis.ticks.length = unit(0.2, "cm"), # Teilstriche
  axis.line = element_line(color = 'black', size = 0.3, linetype = 1) # Achsenlinie
   ) +
  ggtitle("DIL - Relative dose changes in percent from the 1st fraction with DIL") +
  xlab("Fraction") + # X-Achsen-Beschriftung
  ylab("Relative dose changes")   #+ # Y-Achsen-Beschriftung

```





```{r Relative dose changes in Grey from the 1st fraction with Rectum mean,  width=7, height=5, dev=c('png', 'pdf'), message=FALSE}
library(plyr)
library(tidyverse)
library(ggplot2)
library(scales)
library(knitr)
library(kableExtra)
options(digits=3) # zeigt nur drei Zahlenwerte an

Rectum_mean_rel <- read_csv2("data/Rectum_1.csv") # read csv mit europaeischer Syntax. Auf das richtige package achten! 

Rectum_mean_rel <- distinct(Rectum_mean_rel, Mittelwert) # aus dem ursprünglichen tibble wird nur die column Mittelwert behalten


#ddply(DIL_absolut, .(), transform, relchange2 = ((100 / Mittelwert[1]) * Mittelwert) - 100) # alternative Berechnung fuer relative Differenzen zum Ausgangswert in der 1. Reihe 

Rectum_mean_rel <- ddply(Rectum_mean_rel, .(), transform, relchange = ((Mittelwert - Mittelwert[1]) / Mittelwert[1]) * 100) # relative Differenzen zum Ausgangswert in der 1. Reihe werden berechnet

Rectum_mean_rel_table <- ddply(Rectum_mean_rel, .(), transform, relchange = ((Mittelwert - Mittelwert[1]) / Mittelwert[1]) * 100) 



Rectum_mean_rel_table <- Rectum_mean_rel_table %>% rename('Fraction' = '.id') #renmae column '.id' with 'Fraction'

Rectum_mean_rel_table[1:14, 1] = (1:14) 

Rectum_mean_rel_table %>%
  kable(align = c("ccccccccc"), escape = FALSE, format ='html', caption = "Rectum mean descriptive statistics") %>%
kable_styling(bootstrap_options = c("striped", "hover", "condensed"), 
    full_width = TRUE) 



x <- (1:14)
y <- Rectum_mean_rel$relchange

ggplot(Rectum_mean_rel,aes(x=x #DIL_relabs$x
                      ,y=y )) + #DIL_relabs$abschange)) +
   geom_segment( aes(x=x, xend=x, y=0, yend=y), color="black") + # Striche von der Hoehe y bis zu den Punkten
    geom_point() +
  #geom_line() +
 expand_limits(y = c(-5, 10)) +
  scale_y_continuous(breaks = seq(-5, 10, 2.0), labels=function(x) paste0(x,"%")) + #labels=function(x) paste0(x,"%") adds percent symbol, but without multiplying it with 100, like when one does: scale_y_continuous(labels = scales::percent)
    scale_x_continuous(breaks = c(1,5,10,14))  + # adds only specific ticks
  geom_abline(intercept = 0, slope = 0, lty=2) + # horizontale Linie ohne Steigung, da slope = 0 
    theme_classic() +
  theme(
  plot.title =  element_blank(),  #element_text(color="black", size=14, face="bold.italic", family ="serif"), # Titel des Graphen
  axis.text.x = element_text(margin = unit(c(1.5, 0, 0, 0), "mm"), family = "serif", size=rel(2)), # X-Achsen-Bezeichnungs-Parameter
  axis.text.y = element_text(margin = unit(c(0, 1.5, 0, 0), "mm"), family = "serif", size=rel(2)), # Y-Achsen-Bezeichnungs-Parameter
  axis.title.x = element_text(margin = unit(c(1.5, 0, 0, 0), "mm"), family = "serif", size=rel(2)), 
  # X-Achsen-Beschriftungs-(groß)-Parameter
  axis.title.y = element_text(margin = unit(c(0, 2, 0, 0), "mm"), family = "serif", size=rel(2)), # Y-Achsen-Beschriftungs-(groß)-Parameter
  plot.margin = margin(0.5, 0.5, 0.5, 0.5, "cm"), # Abstände um den Graphen in top-right-bottom-left Orientierung
  axis.ticks = element_line(color = 'black', size = 0.5, linetype = 1), axis.ticks.length = unit(0.2, "cm"), # Teilstriche
  axis.line = element_line(color = 'black', size = 0.3, linetype = 1) # Achsenlinie
   ) +
  ggtitle("DIL - Relative dose changes in percent from the 1st fraction with DIL") +
  xlab("Fraction") + # X-Achsen-Beschriftung
  ylab("Relative dose changes")   #+ # Y-Achsen-Beschriftung

```




```{r Relative dose changes in Grey from the 1st fraction with DIL and boost mean POINTS,  width=7, height=5, dev=c('png', 'pdf'), message=FALSE}




p = ggplot() + 
#  geom_line(data = DIL_mean_rel_table, aes(x = 1:14, y = DIL_mean_rel$relchange), color = "blue") +
 # geom_line(data = Boost_mean_rel_table , aes(x = 1:14, y = Boost_mean_rel$relchange), color = "red") +
  #geom_line(data = Rectum_mean_rel_table , aes(x = 1:14, y = Rectum_mean_rel$relchange), color = "green") +
     # geom_point() +
 geom_point(data = DIL_mean_rel_table, aes(x = 1:14, y = DIL_mean_rel$relchange), color = "blue") +
  geom_point(data = Boost_mean_rel_table , aes(x = 1:14, y = Boost_mean_rel$relchange), color = "red") +
  geom_point(data = Rectum_mean_rel_table , aes(x = 1:14, y = Rectum_mean_rel$relchange), color = "green") +
  
  
  expand_limits(y = c(-5, 10)) +
  scale_y_continuous(breaks = seq(-5, 10, 2.0), labels=function(x) paste0(x,"%")) + #labels=function(x) paste0(x,"%") adds percent symbol, but without multiplying it with 100, like when one does: scale_y_continuous(labels = scales::percent)
  
    scale_x_continuous(breaks = c(1,5,10,14))  + # adds only specific ticks
  geom_abline(intercept = 0, slope = 0, lty=2) + # horizontale Linie ohne Steigung, da slope = 0 
    theme_classic() +
  theme(
  plot.title =  element_blank(),  #element_text(color="black", size=14, face="bold.italic", family ="serif"), # Titel des Graphen
  axis.text.x = element_text(margin = unit(c(1.5, 0, 0, 0), "mm"), family = "serif", size=rel(2)), # X-Achsen-Bezeichnungs-Parameter
  axis.text.y = element_text(margin = unit(c(0, 1.5, 0, 0), "mm"), family = "serif", size=rel(2)), # Y-Achsen-Bezeichnungs-Parameter
  axis.title.x = element_text(margin = unit(c(1.5, 0, 0, 0), "mm"), family = "serif", size=rel(2)), 
  # X-Achsen-Beschriftungs-(groß)-Parameter
  axis.title.y = element_text(margin = unit(c(0, 2, 0, 0), "mm"), family = "serif", size=rel(2)), # Y-Achsen-Beschriftungs-(groß)-Parameter
  plot.margin = margin(0.5, 0.5, 0.5, 0.5, "cm"), # Abstände um den Graphen in top-right-bottom-left Orientierung
  axis.ticks = element_line(color = 'black', size = 0.5, linetype = 1), axis.ticks.length = unit(0.2, "cm"), # Teilstriche
  axis.line = element_line(color = 'black', size = 0.3, linetype = 1) # Achsenlinie
   ) +
  ggtitle("DIL - Relative dose changes in percent from the 1st fraction with DIL") +
  xlab("Fraction") + # X-Achsen-Beschriftung
  ylab("Relative dose changes")   #+ # Y-Achsen-Beschriftung


print(p)
    

#df3 <- DIL_rel %>%  mutate(Type = 'Amocycillin') %>%
 #      bind_rows(Boost_mean_rel %>%
  #         mutate(Type = 'Penicillin'))


#ggplot(df3,aes(y = Mittelwert,x = (1:28),color = Type)) + 
#  geom_line() +
 # ggtitle("Merged datasets")

```




```{r Relative dose changes in Grey from the 1st fraction with Bladder mean,  width=7, height=5, dev=c('png', 'pdf'), message=FALSE}
library(plyr)
library(tidyverse)
library(ggplot2)
library(scales)
library(knitr)
library(kableExtra)
options(digits=3) # zeigt nur drei Zahlenwerte an

Bladder_mean_rel <- read_csv2("data/Bladder_1.csv") # read csv mit europaeischer Syntax. Auf das richtige package achten! 

Bladder_mean_rel <- distinct(Bladder_mean_rel, Mittelwert) # aus dem ursprünglichen tibble wird nur die column Mittelwert behalten


#ddply(DIL_absolut, .(), transform, relchange2 = ((100 / Mittelwert[1]) * Mittelwert) - 100) # alternative Berechnung fuer relative Differenzen zum Ausgangswert in der 1. Reihe 

Bladder_mean_rel <- ddply(Bladder_mean_rel, .(), transform, relchange = ((Mittelwert - Mittelwert[1]) / Mittelwert[1]) * 100) # relative Differenzen zum Ausgangswert in der 1. Reihe werden berechnet

Bladder_mean_rel_table <- ddply(Bladder_mean_rel, .(), transform, relchange = ((Mittelwert - Mittelwert[1]) / Mittelwert[1]) * 100) 



Bladder_mean_rel_table <- Bladder_mean_rel_table %>% rename('Fraction' = '.id') #renmae column '.id' with 'Fraction'

Bladder_mean_rel_table[1:14, 1] = (1:14) 

Bladder_mean_rel_table %>%
  kable(align = c("ccccccccc"), escape = FALSE, format ='html', caption = "Bladder mean descriptive statistics") %>%
kable_styling(bootstrap_options = c("striped", "hover", "condensed"), 
    full_width = TRUE) 



x <- (1:14)
y <- Bladder_mean_rel$relchange

ggplot(Bladder_mean_rel,aes(x=x #DIL_relabs$x
                      ,y=y )) + #DIL_relabs$abschange)) +
   geom_segment( aes(x=x, xend=x, y=0, yend=y), color="black") + # Striche von der Hoehe y bis zu den Punkten
    geom_point() +
  #geom_line() +
 expand_limits(y = c(-5, 10)) +
  scale_y_continuous(breaks = seq(-5, 10, 2.0), labels=function(x) paste0(x,"%")) + #labels=function(x) paste0(x,"%") adds percent symbol, but without multiplying it with 100, like when one does: scale_y_continuous(labels = scales::percent)
    scale_x_continuous(breaks = c(1,5,10,14))  + # adds only specific ticks
  geom_abline(intercept = 0, slope = 0, lty=2) + # horizontale Linie ohne Steigung, da slope = 0 
    theme_classic() +
  theme(
  plot.title =  element_blank(),  #element_text(color="black", size=14, face="bold.italic", family ="serif"), # Titel des Graphen
  axis.text.x = element_text(margin = unit(c(1.5, 0, 0, 0), "mm"), family = "serif", size=rel(2)), # X-Achsen-Bezeichnungs-Parameter
  axis.text.y = element_text(margin = unit(c(0, 1.5, 0, 0), "mm"), family = "serif", size=rel(2)), # Y-Achsen-Bezeichnungs-Parameter
  axis.title.x = element_text(margin = unit(c(1.5, 0, 0, 0), "mm"), family = "serif", size=rel(2)), 
  # X-Achsen-Beschriftungs-(groß)-Parameter
  axis.title.y = element_text(margin = unit(c(0, 2, 0, 0), "mm"), family = "serif", size=rel(2)), # Y-Achsen-Beschriftungs-(groß)-Parameter
  plot.margin = margin(0.5, 0.5, 0.5, 0.5, "cm"), # Abstände um den Graphen in top-right-bottom-left Orientierung
  axis.ticks = element_line(color = 'black', size = 0.5, linetype = 1), axis.ticks.length = unit(0.2, "cm"), # Teilstriche
  axis.line = element_line(color = 'black', size = 0.3, linetype = 1) # Achsenlinie
   ) +
  ggtitle("DIL - Relative dose changes in percent from the 1st fraction with DIL") +
  xlab("Fraction") + # X-Achsen-Beschriftung
  ylab("Relative dose changes")   #+ # Y-Achsen-Beschriftung

```



```{r Relative dose changes in Grey from the 1st fraction with DIL and boost mean lines,  width=7, height=5, dev=c('png', 'pdf'), message=FALSE}




p = ggplot() + 
  geom_line(data = DIL_mean_rel_table, aes(x = 1:14, y = DIL_mean_rel$relchange), color = "blue") +
  geom_line(data = Boost_mean_rel_table , aes(x = 1:14, y = Boost_mean_rel$relchange), color = "red") +
  geom_line(data = Rectum_mean_rel_table , aes(x = 1:14, y = Rectum_mean_rel$relchange), color = "green") +
    geom_line(data = Bladder_mean_rel_table, aes(x = 1:14, y = Bladder_mean_rel$relchange), color = "orange") +
     # geom_point() +
 geom_point(data = DIL_mean_rel_table, aes(x = 1:14, y = DIL_mean_rel$relchange), color = "blue") +
  geom_point(data = Boost_mean_rel_table , aes(x = 1:14, y = Boost_mean_rel$relchange), color = "red") +
 geom_point(data = Rectum_mean_rel_table , aes(x = 1:14, y = Rectum_mean_rel$relchange), color = "green") +
   geom_point(data = Bladder_mean_rel_table, aes(x = 1:14, y = Bladder_mean_rel$relchange), color = "orange") +
  
  expand_limits(y = c(-5, 10)) +
  scale_y_continuous(breaks = seq(-5, 10, 2.0), labels=function(x) paste0(x,"%")) + #labels=function(x) paste0(x,"%") adds percent symbol, but without multiplying it with 100, like when one does: scale_y_continuous(labels = scales::percent)
  
    scale_x_continuous(breaks = c(1,5,10,14))  + # adds only specific ticks
  geom_abline(intercept = 0, slope = 0, lty=2) + # horizontale Linie ohne Steigung, da slope = 0 
    theme_classic() +
  theme(
  plot.title =  element_blank(),  #element_text(color="black", size=14, face="bold.italic", family ="serif"), # Titel des Graphen
  axis.text.x = element_text(margin = unit(c(1.5, 0, 0, 0), "mm"), family = "serif", size=rel(2)), # X-Achsen-Bezeichnungs-Parameter
  axis.text.y = element_text(margin = unit(c(0, 1.5, 0, 0), "mm"), family = "serif", size=rel(2)), # Y-Achsen-Bezeichnungs-Parameter
  axis.title.x = element_text(margin = unit(c(1.5, 0, 0, 0), "mm"), family = "serif", size=rel(2)), 
  # X-Achsen-Beschriftungs-(groß)-Parameter
  axis.title.y = element_text(margin = unit(c(0, 2, 0, 0), "mm"), family = "serif", size=rel(2)), # Y-Achsen-Beschriftungs-(groß)-Parameter
  plot.margin = margin(0.5, 0.5, 0.5, 0.5, "cm"), # Abstände um den Graphen in top-right-bottom-left Orientierung
  axis.ticks = element_line(color = 'black', size = 0.5, linetype = 1), axis.ticks.length = unit(0.2, "cm"), # Teilstriche
  axis.line = element_line(color = 'black', size = 0.3, linetype = 1) # Achsenlinie
   ) +
  ggtitle("DIL - Relative dose changes in percent from the 1st fraction with DIL") +
  xlab("Fraction") + # X-Achsen-Beschriftung
  ylab("Relative dose changes")   #+ # Y-Achsen-Beschriftung


print(p)
    

#df3 <- DIL_rel %>%  mutate(Type = 'Amocycillin') %>%
 #      bind_rows(Boost_mean_rel %>%
  #         mutate(Type = 'Penicillin'))


#ggplot(df3,aes(y = Mittelwert,x = (1:28),color = Type)) + 
#  geom_line() +
 # ggtitle("Merged datasets")

```

```{r linear regression Rectum DIL means,  width=7, height=5, dev=c('png', 'pdf'), message=FALSE}

plot(Rectum_mean_rel$relchange, DIL_mean_rel$relchange)


fm <- lm(y ~ x)

lm(formula = y ~ x)

fitted.values(fm)
residuals(fm)

summary(fm)


plot(x, y)
abline(fm, col = "red")


```


```{r linear regression Bladder DIL means,  width=7, height=5, dev=c('png', 'pdf'), message=FALSE}

plot(Bladder_mean_rel$relchange, DIL_mean_rel$relchange)


fn <- lm(y ~ x)

lm(formula = y ~ x)

fitted.values(fn)
residuals(fn)

summary(fn)


plot(x, y)
abline(fn, col = "red")


```


```{r linear regression Boost DIL means,  width=7, height=5, dev=c('png', 'pdf'), message=FALSE}

plot(Boost_mean_rel$relchange, DIL_mean_rel$relchange)


fo <- lm(y ~ x)

lm(formula = y ~ x)

fitted.values(fo)
residuals(fo)

summary(fo)


plot(x, y)
abline(fo, col = "red")


```

DIL_mean_rel$relchange
Rectum_mean_rel$relchange

